# Generated by Django 5.1 on 2025-04-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], max_length=20)),
                ('meeting_datetime', models.DateTimeField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('participants', models.TextField(help_text='List of participants/attendees, separated by commas')),
                ('location_or_link', models.CharField(help_text='Meeting location or online meeting link', max_length=300)),
                ('agenda_items', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='meeting_attachments/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('recording', models.FileField(blank=True, null=True, upload_to='meeting_recordings/')),
            ],
        ),
        migrations.CreateModel(
            name='meetingschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_name', models.CharField(max_length=255)),
                ('Datetime', models.DateTimeField()),
                ('Organizer', models.CharField(max_length=255)),
                ('Participants', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('registrar', 'Registrar'), ('vice_chancellor', 'Vice Chancellor')], max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
