# Generated by Django 5.1 on 2025-04-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetingcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('importance', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='meetingschedule',
        ),
    ]
