# Generated by Django 5.1 on 2025-04-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0003_remove_meetingform_organizer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingform',
            name='recording',
        ),
        migrations.AlterField(
            model_name='meetingform',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_app.meetingcategory'),
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(upload_to='meeting_recordings/')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meeting_app.meetingform')),
            ],
        ),
    ]
