# Generated by Django 5.1 on 2025-05-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0004_remove_meetingform_recording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationname', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingform',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='meetingrecording',
            name='meeting',
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting_app.designation'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='groups', to='meeting_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_marks', models.IntegerField()),
                ('poster_marks', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='meeting_app.group')),
            ],
        ),
        migrations.DeleteModel(
            name='meetingcategory',
        ),
        migrations.DeleteModel(
            name='MeetingForm',
        ),
        migrations.DeleteModel(
            name='MeetingRecording',
        ),
    ]
