# Generated by Django 5.1 on 2025-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0005_designation_remove_meetingform_meeting_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members_names',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
