# Generated by Django 5.1 on 2025-05-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0006_remove_group_members_group_members_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='meeting_app.user'),
            preserve_default=False,
        ),
    ]
