# Generated by Django 4.2.21 on 2025-05-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0007_marks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
